spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:3306/vest-reports
    username: root
    password: bcd127
  jackson:
    default-property-inclusion: non_null
jwt:
  secret: 2c57cf3a-c804-4dc5-8cd4-93b8d8581948
  expiration: 999999